### ISSUE TITLE
Processing dunkleosteus dna produces unknown object.

### ISSUE THREAD

**Issue by daytonnvpaul** [ElCeejoYT/paleotest#3]
Seems like the routine is missing.  Is it scheduled for future updates?

**Comment by ElCeejoYT** [comment]
Pretty sure I fixed that a while ago. Make sure you're using the latest version of the mod.

**Comment by daytonnvpaul** [comment]
Slight error on my part, it was the Dilophosaurus.  Player gave me the incorrect item name. I had to identify the issue on my own.

BTW, mod updated on my server on Oct 3rd

**Comment by rusty-snake** [comment]
The issue still remains. It's noticeable that there is no `dilophosaurus.lua` cf.
https://github.com/ElCeejo/paleotest/search?q=Dilophosaurus&unscoped_q=Dilophosaurus
https://github.com/ElCeejo/paleotest/search?q=Tyrannosaurus&unscoped_q=Tyrannosaurus
